development:
  adapter: postgresql
  encoding: utf8
  database: learning-app_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: learning-app_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: learning-app_production
  pool: 5
  username:
  password:
